### ISSUE TITLE
Add "ATTENDEE" user stories and storyboard mockups for stories below:

### ISSUE THREAD

**Issue by uabaz** [Team4GPA/SeQR#2]
Attendee:

US 02.01.01 As an attendee, I want to quickly check into an event by scanning the provided QR code.

US 02.02.01 As an attendee, I want to upload a profile picture for a more personalized experience.

US 02.02.02 As an attendee, I want to remove profile pictures if need be.

US 02.02.03 As an attendee, I want to update information such as name, homepage, and contact information on my profile.

US 02.03.01 As an attendee, I want to receive push notifications with important updates from the event organizers.

US 02.04.01 As an attendee, I want to view event details and announcements within the app.

US 02.05.01 As an attendee, I want my profile picture to be deterministically generated from my profile name if I haven't uploaded an profile image yet.

US 02.06.01 As an attendee, I do not want to login to the app. No username, no password.

**Comment by GMRafay** [comment]
https://app.moqups.com/AYYsENVmD8SHya7Odv7X0B1BpYKfGKKu/view/page/ad64222d5

Here is the Attendees user stories and storyboard mockups.

**Comment by Xunzer** [comment]
Done, for part 3 we can open a new issue
