### ISSUE TITLE
Organizer US 01.06.01 : Share a generator QR code image to other apps to email or update other documents with the QR code

### ISSUE THREAD

**Issue by Xunzer** [Team4GPA/SeQR#21]
Organizer US 01.06.01 As an organizer, I want to share a generator QR code image to other apps so I can email or update other documents with the QR code.

# ESTIMATED SIZE
15 story points

# ACCEPTANCE CRITERIA
TBD

# IMPLIED:
QR code generator
QR code to an image (like a PNG?)
Ability to share to other apps - could be a button at the UI bottom / long click to share
Implement the share intent so you can use other android apps with this image that you generated
Including both the check-in QR and promo QR

# CONSIDERATIONS:
How to achieve this functionality? By using some API?
What kind of apps can the QR code be ported to?
Seems to be a very generic functionality among mobile apps but need to figure out a way to achieve this
Do we keep a log of sharing into other apps?
Do we keep a log of who is sharing?

-R.L

**Comment by uabaz** [comment]
Finished this with a shareSheet and custom FileProvider class
