### ISSUE TITLE
Attendee US 02.01.01 Quickly check into an event by scanning the provided QR code

### ISSUE THREAD

**Issue by Xunzer** [Team4GPA/SeQR#25]
US 02.01.01 As an attendee, I want to quickly check into an event by scanning the provided QR code

# ESTIMATED SIZE
20 story points

# ACCEPTANCE CRITERIA
TBD

# IMPLIED:
Need API scanning the QR code
Convert the QR code picture into a link to check in webpage
Once attendee logins in to that webpage, it will be seen as a checked in
Automatic check in on both attendee and organizer side after scanning
real time update the UI on organizer size - Firebase needed
message on attendee side like "successfully checked in"
Set status for each attendee profile

# CONSIDERATIONS:
What API should we use?
How do we update it in real time?
Generation of QR code image and store the check in webpage in the image
Different event with different QR code picture
Need access of user's camera
Firebase update

-R.L

**Comment by uabaz** [comment]
This is complete thanks to Ahmed
