### ISSUE TITLE
Organize a Storyboard graphic that displays all stories and their connections (UI Mockups / Storyboard Sequences)

### ISSUE THREAD

**Issue by uabaz** [Team4GPA/SeQR#5]
- One graphic, or many?
- What software to generate UI Mockups (quickly, cheaply, consistently)?
- Who is responsible?
- Does the storyboard sequence cover all Story requirements?

**Comment by uabaz** [comment]
Possible mockup software:

- Canva.com (https://www.canva.com/design/DAF8I9n-i4M/l-MybvEHWWKC6WcIrlJzPA/edit?utm_content=DAF8I9n-i4M&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- Moqups.com (https://app.moqups.com/xFh7u9Xu1zZ3YrVfYxQde3PYBpD4nFAA/view/page/a68a9648a)
- Proto.io (https://share.proto.io/17M2HF/)
- Figma (https://www.figma.com/file/RzozjjRFrVFnYc8NSTgP9m/Figma-basics?type=design&node-id=4368%3A321189&mode=design&t=gwhhs951Aj5w3iKj-1)

**Comment by GMRafay** [comment]
https://app.moqups.com/hp2TRRScZi7KTswejZqIuLcYdFE2WzZP/view/page/ad64222d5

Link for UI mockup

**Comment by GMRafay** [comment]
Made some of the UI mockup for the Attendees user experience, check it out and we can see where to improve and what to add ^
