### ISSUE TITLE
Create "Backlog" of GitHub "issues" to create a work-back schedule for the entire project

### ISSUE THREAD

**Issue by uabaz** [Team4GPA/SeQR#7]
- What milestones/dates for app features?
- What user stories will take the most time?
- What implementations will take the most time?
- How many people can work on a issue at a time?
- Delegation of tasks
- Consistency between UI's and behaviors
- Halfway Point app demonstration wishlist: what point should we aim for?

NUMBER THE BACKLOG TASKS 
0. Design and UI preferences and essentials; 
1. Basic model done; 
2. Add all Attendee features; 
3. Add all Organizer features; 
4.  mid-way demonstration; 
5. Add all Administrator features; 
6. bugtest and add wishlist/polish; 
7. final application demonstration and hand-in
8. end of term celebration

**Comment by Xunzer** [comment]
Done
https://github.com/Team4GPA/SeQR/wiki/Part-2:-Product-Backlog
I think we can close this issue now?
